### ISSUE TITLE
Publish arm docker image

### ISSUE THREAD

**Issue by cunla** [jansorg/marketplace-stats-kotlin#45]
Hi, would it be possible to publish a docker image for arm machines?

**Comment by jansorg** [comment]
Yes, that should be possible even from an amd64 machine. Do you happen to know how to do this? :smile:

**Comment by cunla** [comment]
Use a universal base image. 
`eclipse-temurin/17-alpine` has only `amd64`, 
`eclipse-temurin/17-jdk` has `arm64` support.

I can create a PR for it if you want.

**Comment by jansorg** [comment]
Thanks! I'll try to go with `eclipse-temurin:17-jre` to make it a bit smaller. I'll try this later today.

**Comment by jansorg** [comment]
I switched to `docker buildx` and hopefully published a multi-platform container, https://hub.docker.com/r/jansorg/jetbrains-marketplace-stats/tags
Please test and let me know if it's working for you.
(It's using JRE21 now)
