### ISSUE TITLE
Support for multiple plugins

### ISSUE THREAD

**Issue by AntonShuvaev** [jansorg/marketplace-stats-kotlin#9]

**Comment by jansorg** [comment]
Could you elaborate what kind of support you'd like? For example, a combined report for all plugins or the same pages for each plugin?

**Comment by AntonShuvaev** [comment]
The same pages for each plugin. Actually, I've already made a simple implementation of it, and I can create a PR.

**Comment by jansorg** [comment]
This is implemented by https://github.com/jansorg/marketplace-stats-kotlin/commit/87234b8573973bb8119285056a01c52c1f1bcca8, but I'll add a few follow-up issues for improvements

**Comment by AntonShuvaev** [comment]
Thanks!
